import type { Metadata, Viewport } from "next";
import { FloatingBottomActions } from "./components/common/FloatingBottomActions";
import { HomeGatewayProvider } from "./components/common/HomeGatewayProvider";
import { SmoothScrollProvider } from "./components/common/SmoothScrollProvider";
import "./globals.css";
import "remixicon/fonts/remixicon.css";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export const metadata: Metadata = {
  title: "Sanskar Group",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/sankar_favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-full bg-white antialiased" suppressHydrationWarning>
        <SmoothScrollProvider>
          <HomeGatewayProvider>
            {children}
            <FloatingBottomActions />
          </HomeGatewayProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
